url: https://hyperiongeo.github.io
baseurl: /agency-jekyll-theme/

# Site settings
title: Hyperion GeoServices Corp
email: hyperion.geo@gmail.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Corey Hooge
  pic: 1
  position: Senior Consulting Geophysicist
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: github
    url: http://github.com/hyperiongeo

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Calgary, AB

# Build settings
markdown: kramdown
permalink: pretty
